#!/bin/sh

echo ln -sf  ../../hooks-available/post-commit-auto-push $HOME/.config/vcsh/repo.d/${VCSH_DIRECTORY}.git/hooks/post-commit
ln -sf  ../../../hooks-available/post-commit-auto-push $HOME/.config/vcsh/repo.d/${VCSH_DIRECTORY}.git/hooks/post-commit
